<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\UsahaController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\KBLIPusdatin;
use App\Http\Controllers\SocialiteController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\TrackingController;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/kbli/{subzona}', [KBLIPusdatin::class, 'kegiatan']);
Route::get('/kbli/{subzona}/{kegiatan}', [KBLIPusdatin::class, 'skala']);
Route::get('/kbli/{subzona}/{kegiatan}/{skala}', [KBLIPusdatin::class, 'kewenangan']);


// login dengan google
Route::get('/auth/redirect', [SocialiteController::class, 'redirectToProvider'])->name('login-google');
Route::get('/auth/callback', [SocialiteController::class, 'handleProviderCallback']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', function (Request $request) {
    return view('layout.main');
});

Route::get('/migrasi', function () {
    $data = array(
        0 => array('Nama' => 'A\'Yun Sita Rosa', 'Email' => 'ayunsitarosa@gmail.com'),
        1 => array('Nama' => 'Abdul Gofur', 'Email' => 'a.ghofur1489@gmail.com'),
        2 => array('Nama' => 'Abdul Rahman Siddik Nazara', 'Email' => 'rhmnsddk@gmail.com'),
        3 => array('Nama' => 'Abdul Refli Gunawan', 'Email' => 'abdul.refli@gmail.com'),
        4 => array('Nama' => 'Abyan Bahy Day Taqy', 'Email' => 'Abyan.bdt@gmail.com'),
        5 => array('Nama' => 'Achmad Badrian', 'Email' => 'achmadbadrian@gmail.com'),
        6 => array('Nama' => 'Achmad Try Laksana', 'Email' => 'achmadtryl22@gmail.com'),
        7 => array('Nama' => 'Ade Lilis Suryani', 'Email' => 'adelilissuryani07@gmail.com'),
        8 => array('Nama' => 'Ade Usep Herdiana', 'Email' => 'adheusep@gmail.com'),
        9 => array('Nama' => 'Adhamaski Pangeran', 'Email' => 'adhamaskipangeran@Gmail.com'),
        10 => array('Nama' => 'Adhi Isayadi', 'Email' => 'adhiisayadi@gmail.com'),
        11 => array('Nama' => 'Aditya Wibisono', 'Email' => 'adittvc@gmail.com'),
        12 => array('Nama' => 'Adityo Wibowo', 'Email' => 'tamaadit33@gmail.com'),
        13 => array('Nama' => 'Agus Budiono', 'Email' => 'budhyono1290@gmail.com'),
        14 => array('Nama' => 'Agus Tarpindo', 'Email' => 'tarpindoita@gmail.com'),
        15 => array('Nama' => 'Agus Taruna', 'Email' => 'tarunaagus2011@gmail.com'),
        16 => array('Nama' => 'Ahmad Fahri Rizkia', 'Email' => 'fahririzkia@gmail.com'),
        17 => array('Nama' => 'Ahmad Faruk', 'Email' => 'faruqahmad44@gmail.com'),
        18 => array('Nama' => 'Ahmad Fauzi', 'Email' => 'ahmadfauzanauliaa@gmail.com'),
        19 => array('Nama' => 'Ahmad Fauzan Aulia', 'Email' => 'singforfreedom10@gmail.com'),
        20 => array('Nama' => 'Ahmad Jauhari', 'Email' => 'ajawwller20@gmail.com'),
        21 => array('Nama' => 'Ahmad Rosdianto', 'Email' => 'rosdianto07@gmail.com'),
        22 => array('Nama' => 'Ainul Basyirah', 'Email' => 'basyirah14041988@gmail.com'),
        23 => array('Nama' => 'Alan Reno Mutthoha', 'Email' => 'alanmutthoha94@gmail.com'),
        24 => array('Nama' => 'Alfian Sururi Achmad', 'Email' => 'alsururi.ach@gmail.com'),
        25 => array('Nama' => 'Alfian Wahyu Prayugha', 'Email' => 'alfianwahyu83@gmail.com'),
        26 => array('Nama' => 'Alfianulingga', 'Email' => 'alfianulingga@gmail.com'),
        27 => array('Nama' => 'Aliffa Ilfan Rachmat', 'Email' => 'aliffailfanr2323@gmail.com'),
        28 => array('Nama' => 'Amirah Zahidah', 'Email' => 'amirahzahidah8@gmail.com'),
        29 => array('Nama' => 'Andie Arie Ashari Putra Pratama', 'Email' => 'andi.putrapratama18@gmail.com'),
        30 => array('Nama' => 'Andri Kurniawan', 'Email' => 'andri12103670@gmail.com'),
        31 => array('Nama' => 'Angga Fazar Ramadhan', 'Email' => 'anggafazarrr.af97@gmail.com'),
        32 => array('Nama' => 'Angga Triandi', 'Email' => 'angga.triandi@gmail.com'),
        33 => array('Nama' => 'Anggi Dwi Kusmawanto', 'Email' => 'Anggidwikusumawanto@gmail.com'),
        34 => array('Nama' => 'Anggi Prawira', 'Email' => 'anggi.prawira01@gmail.com'),
        35 => array('Nama' => 'Anggit Refo Kurniawan', 'Email' => 'anggitrefokurniawan@gmail.com'),
        36 => array('Nama' => 'Ardian Rezaldi', 'Email' => 'ardian.rezaldi@gmail.com'),
        37 => array('Nama' => 'Arham', 'Email' => 'alansembilanpuluh90@gmail.com'),
        38 => array('Nama' => 'Arie Kurniawan', 'Email' => 'arie111184kurniawan@gmail.com'),
        39 => array('Nama' => 'Arief Tri Suprayoga', 'Email' => 'arieftrisuprayoga@gmail.com'),
        40 => array('Nama' => 'Arrahman Fadilah', 'Email' => 'arrfdlh98@gmail.com'),
        41 => array('Nama' => 'Arya Putra Hutama S', 'Email' => 'aryaputrahutama28@gmail.com'),
        42 => array('Nama' => 'Aryo Yudanto', 'Email' => 'aryoyudanto12@gmail.com'),
        43 => array('Nama' => 'As’ad Najmudin', 'Email' => 'aatnajm@gmail.com'),
        44 => array('Nama' => 'Asep Karis Choliludin', 'Email' => 'asep.karis@gmail.com'),
        45 => array('Nama' => 'Asep Sofyan', 'Email' => 'asepsofyan565@gmail.com'),
        46 => array('Nama' => 'Asriani Istika Putri', 'Email' => 'asrianiistika@gmail.com'),
        47 => array('Nama' => 'Aswin Fadillah', 'Email' => 'aswinreborn81@gmail.com'),
        48 => array('Nama' => 'Bagoes Irawan Tejamukti', 'Email' => 'bagoezirawan@gmail.com'),
        49 => array('Nama' => 'Bagus Jatnika', 'Email' => 'bagusbenner@gmail.com'),
        50 => array('Nama' => 'Baihaqi Budiman', 'Email' => 'baihaqibudiman@gmail.com'),
        51 => array('Nama' => 'Basuki', 'Email' => 'basukipondokungu@gmail.com'),
        52 => array('Nama' => 'Billy Ardian Putra', 'Email' => 'billy150680@gmail.com'),
        53 => array('Nama' => 'Btara Anggareksa Widyandhana', 'Email' => 'eltobtara19@gmail.com'),
        54 => array('Nama' => 'Budi Hartanto', 'Email' => 'budihartanto179@gmail.com'),
        55 => array('Nama' => 'Budi Sulistiyono', 'Email' => 'budisyn@gmail.com'),
        56 => array('Nama' => 'Chrissandy Haryanto Sinambela', 'Email' => 'chrissandysinambela22@gmail.com'),
        57 => array('Nama' => 'Dandy Reza Permana Putra', 'Email' => 'dandyreza73@gmail.com'),
        58 => array('Nama' => 'Daniel Harvey Tulis', 'Email' => 'danieltulis1000@gmail.com'),
        59 => array('Nama' => 'David Hendra Jaya', 'Email' => 'davidhendrajayasikumbang@gmail.com'),
        60 => array('Nama' => 'Dear Angela', 'Email' => 'dearangela581@gmail.com'),
        61 => array('Nama' => 'Deddy Indrawan', 'Email' => 'indrawandeddy@rocketmail.com'),
        62 => array('Nama' => 'Dedi', 'Email' => 'bbalee11@gmail.com'),
        63 => array('Nama' => 'Dewinta Cahya Mardlatilla', 'Email' => 'dewintacaca@gmail.com'),
        64 => array('Nama' => 'Dhimas Ali Fadhilah', 'Email' => 'dhimasalifadhilah@gmail.com'),
        65 => array('Nama' => 'Diah Ayu Retno Wati', 'Email' => 'diaharw13@gmail.com'),
        66 => array('Nama' => 'Dicky Mustofa Nurul Sadikin', 'Email' => 'dicky.mustofa90@gmail.com'),
        67 => array('Nama' => 'Dikdik Suratman', 'Email' => 'dikdik@myself.com'),
        68 => array('Nama' => 'Dima Syauqi Nuralif Hendradi', 'Email' => 'syauqidima27@gmail.com'),
        69 => array('Nama' => 'Dini Asrianti', 'Email' => 'diniasrianti12@gmail.com'),
        70 => array('Nama' => 'Dohar Paima Sitorus', 'Email' => 'doharpaimasitorus@gmail.com'),
        71 => array('Nama' => 'Dzikru Shodikin', 'Email' => 'dzikru2140@gmail.com'),
        72 => array('Nama' => 'Endang Sanjaya', 'Email' => 'endangsanjaya2012@gmail.com'),
        73 => array('Nama' => 'Erlangga Abadi Perkasa', 'Email' => 'erlanggaabadip@gmail.com'),
        74 => array('Nama' => 'Erol Yusuf Aditama Fabanyo', 'Email' => 'ey6605@gmail.com'),
        75 => array('Nama' => 'Esa Wahyu Juliantoro', 'Email' => 'esa.wahyu.j@gmail.com'),
        76 => array('Nama' => 'Fachry Faqihatur Ridwan', 'Email' => 'fachry.ptsp@gmail.com'),
        77 => array('Nama' => 'Fadhil Razan Wibyfari', 'Email' => 'fadhilrzn@gmail.com'),
        78 => array('Nama' => 'Fadhillah Royhan Abdurrasyid', 'Email' => 'abdurrasyid4897@gmail.com'),
        79 => array('Nama' => 'Fahmi Lukmanul Hakim', 'Email' => 'fahmilukmanulhakim4@gmail.com'),
        80 => array('Nama' => 'Faidal', 'Email' => 'ladiaf@gmail.com'),
        81 => array('Nama' => 'Faiz Akmal Fadhlur Rahman', 'Email' => 'faiz.akmalfr26@gmail.com'),
        82 => array('Nama' => 'Faiz Husnayain', 'Email' => 'faizhusnayain28@gmail.com'),
        83 => array('Nama' => 'Fajar Ramadhan Dayly Alfikri', 'Email' => 'ramadhandaylial@gmail.com'),
        84 => array('Nama' => 'Faozi Latif', 'Email' => 'faozilatif53@gmail.com'),
        85 => array('Nama' => 'Farida Lestari', 'Email' => 'faridalestaribigbang@gmail.com'),
        86 => array('Nama' => 'Fariz Kurniawan', 'Email' => 'fariz.kurni.14@gmail.com'),
        87 => array('Nama' => 'Fauzan Rizqiyanto', 'Email' => 'fauzanrizqiyanto@yahoo.com'),
        88 => array('Nama' => 'Fauzan Syarif', 'Email' => 'jkt.fsma@gmail.com'),
        89 => array('Nama' => 'Faza Alifziano', 'Email' => 'faza.alifziano@gmail.com'),
        90 => array('Nama' => 'Febrianto Matondang', 'Email' => 'febx02@gmail.com'),
        91 => array('Nama' => 'Fendi Aji Saputra', 'Email' => 'masfendi1994@gmail.com'),
        92 => array('Nama' => 'Fendi Putama', 'Email' => 'fendiputama.fp@gmail.com'),
        93 => array('Nama' => 'Ferdi Prabowo Kaeyadebi', 'Email' => 'fkaeyadebi@gmail.com'),
        94 => array('Nama' => 'Fernando Tri Tanjung', 'Email' => 'fernandotritanjung@gmail.com'),
        95 => array('Nama' => 'Fery Andriyanto', 'Email' => 'feryandriyanto09@gmail.com'),
        96 => array('Nama' => 'Fidiyati', 'Email' => 'fidi.azzahra@gmail.com'),
        97 => array('Nama' => 'Fikri Hendhiyanto Yuliansyah', 'Email' => 'fikrihendhiyantoyuliansyah@gmail.com'),
        98 => array('Nama' => 'Frendo Rajagukguk', 'Email' => 'frendorajagukguk96@gmail.com'),
        99 => array('Nama' => 'Ghean Azrin Mirza', 'Email' => 'gheanazrin17@gmail.com'),
        100 => array('Nama' => 'Grace Rebekah', 'Email' => 'gracepardede007@gmail.com'),
        101 => array('Nama' => 'Gusti Oktajayanto', 'Email' => 'gusti.batman@gmail.com'),
        102 => array('Nama' => 'Hafizh Prastyo Yudotomo', 'Email' => 'hafizh.prastyo@gmail.com'),
        103 => array('Nama' => 'Handrianus Tm Wolo', 'Email' => 'handrianus.wolo@gmail.com'),
        104 => array('Nama' => 'Hanif Ibnu Fajar', 'Email' => 'hanif.fajar.id@gmail.com'),
        105 => array('Nama' => 'Harry Akbar Luhulima', 'Email' => 'harryluhulima13@gmail.com'),
        106 => array('Nama' => 'Harry Setiadi', 'Email' => 'harry.setiadi.bkc@gmail.com'),
        107 => array('Nama' => 'Hening Panghegar', 'Email' => 'panghegarthanthowi@gmail.com'),
        108 => array('Nama' => 'Hesti Windy Lestari', 'Email' => 'hestiwindylestari@gmail.com'),
        109 => array('Nama' => 'Hesyah Iqra Rani', 'Email' => 'hesyair@gmail.com'),
        110 => array('Nama' => 'Hinsa Nurhijriani Hasibuan', 'Email' => 'hinsanur@gmail.com'),
        111 => array('Nama' => 'Ifvoni', 'Email' => 'vonyganiu@gmail.com'),
        112 => array('Nama' => 'Ilman Nugraha', 'Email' => 'ilmannugraha178@gmail.com'),
        113 => array('Nama' => 'Imam Ghozalih', 'Email' => 'imamghzh@gmail.com'),
        114 => array('Nama' => 'Imam Marufi', 'Email' => 'imammarufi1996@gmail.com'),
        115 => array('Nama' => 'Imam Mutawalli Assyarawi', 'Email' => 'mamsimam28@gmail.com'),
        116 => array('Nama' => 'Imas Nuraini', 'Email' => 'imasnuraini16@gmail.com'),
        117 => array('Nama' => 'Indra Ardiyanto', 'Email' => 'indraardiyanto88@gmail.com'),
        118 => array('Nama' => 'Indra Wijaya', 'Email' => 'indrawijya712@gmail.com'),
        119 => array('Nama' => 'Innes Resnasari Agustianty', 'Email' => 'innesresnasari@gmail.com'),
        120 => array('Nama' => 'Ipung Jatti Renanda', 'Email' => 'ipung.jatti@gmail.com'),
        121 => array('Nama' => 'Iris Ronya Oktavia', 'Email' => 'irisronyaoktavia1010@gmail.com'),
        122 => array('Nama' => 'Ismail Marjuki', 'Email' => 'ismailmarjuki2013@gmail.com'),
        123 => array('Nama' => 'Jefry Maulana', 'Email' => 'jefrymaulana17@gmail.com'),
        124 => array('Nama' => 'Juan Ernest', 'Email' => 'juanpasaribu1296@gmail.com'),
        125 => array('Nama' => 'Jumi Yani', 'Email' => 'zumieyani@gmail.com'),
        126 => array('Nama' => 'Kadrin', 'Email' => 'kadha6666@gmail.com'),
        127 => array('Nama' => 'Kamaludin Siregar', 'Email' => 'rizal.dipiya@gmail.com'),
        128 => array('Nama' => 'Kartika Puspa Dewi', 'Email' => 'kartikapuspadewi23@gmail.com'),
        129 => array('Nama' => 'Kemri Purba', 'Email' => 'kemripurba@gmail.com'),
        130 => array('Nama' => 'Lady Sarah', 'Email' => 'ladysarah1925@gmail.com'),
        131 => array('Nama' => 'Lail Fajri', 'Email' => 'lail.fajri05@gmail.com'),
        132 => array('Nama' => 'Lia Maulinah Angriani', 'Email' => 'limaumau10@gmail.com'),
        133 => array('Nama' => 'Lukman Arief Gunawan', 'Email' => 'lukman066@gmail.com'),
        134 => array('Nama' => 'Lutfi Firdaus', 'Email' => 'lutfifirdaus16881@gmail.com'),
        135 => array('Nama' => 'Luthfi Alhamza Taneo', 'Email' => 'alhamzaluthfi83@gmail.com'),
        136 => array('Nama' => 'M. Assadulloh S.Kom.', 'Email' => 'm.assadulloh@gmail.com'),
        137 => array('Nama' => 'M. Raimi Said', 'Email' => 'raimisaid@gmail.com'),
        138 => array('Nama' => 'M. Sulhi Purnama', 'Email' => 'sulhipurnama@gmail.com'),
        139 => array('Nama' => 'M.Ardiansyah Aloetsyah', 'Email' => 'ardiansyahaloetsyah@gmail.com'),
        140 => array('Nama' => 'Maraden Manurung', 'Email' => 'maraden.manurung28@gmail.com'),
        141 => array('Nama' => 'Masayu Nadya Ardelya Kesuma', 'Email' => 'msynadyaardelyakesuma@gmail.com'),
        142 => array('Nama' => 'Maudy Zuraeva', 'Email' => 'maudyzuraeva@gmail.com'),
        143 => array('Nama' => 'Mawandri Sardi', 'Email' => 'mawandri888@gmail.com'),
        144 => array('Nama' => 'Mochammad Sofi', 'Email' => 'm.17sofi@gmail.com'),
        145 => array('Nama' => 'Mohamad Fajar Ramadhan', 'Email' => 'mhdfajarrmdhn@gmail.com'),
        146 => array('Nama' => 'Mohammad Tri Andika', 'Email' => 'dika.zoldick@gmail.com'),
        147 => array('Nama' => 'Muh.Rafli Fachrozi', 'Email' => 'rafli.fachrozi25@gmail.com'),
        148 => array('Nama' => 'Muhamad Mashud', 'Email' => 'mashud0429@gmail.com'),
        149 => array('Nama' => 'Muhamad Nazi', 'Email' => 'muhammadnazi1989@gmail.com'),
        150 => array('Nama' => 'Muhamad Nur Assyidiq', 'Email' => 'sidikmio90@gmail.com'),
        151 => array('Nama' => 'Muhamad Nur Awali', 'Email' => 'dimasnoorawali@gmail.com'),
        152 => array('Nama' => 'Muhamad Suni Fauzi', 'Email' => 'msunifauzii17@gmail.com'),
        153 => array('Nama' => 'Muhamad Trio Sakti', 'Email' => 'muhammadtriosakti@gmail.com'),
        154 => array('Nama' => 'Muhammad Abduh', 'Email' => 'mhmd.abduh98@gmail.com'),
        155 => array('Nama' => 'Muhammad Adam Maulana', 'Email' => 'm.adammaulanna@gmail.com'),
        156 => array('Nama' => 'Muhammad Amri Cahyo Gumilar', 'Email' => 'amri.cahyo@gmail.com'),
        157 => array('Nama' => 'Muhammad Arif Setiawan', 'Email' => 'marifsetiawan75@gmail.com'),
        158 => array('Nama' => 'Muhammad Beri Ferari', 'Email' => 'mberiferari@gmail.com'),
        159 => array('Nama' => 'Muhammad Deni Nusantara', 'Email' => 'deni.nusantara46@yahoo.com'),
        160 => array('Nama' => 'Muhammad Fajriyansyah', 'Email' => 'mfajriyansyah2905@gmail.com'),
        161 => array('Nama' => 'Muhammad Farhan Kurniawan', 'Email' => 'muh.farhankurniawan@gmail.com'),
        162 => array('Nama' => 'Muhammad Febrianto Herinanda Putra', 'Email' => 'm.febrianto.97@gmail.com'),
        163 => array('Nama' => 'Muhammad Haryadi', 'Email' => 'm.haryadi88@gmail.com'),
        164 => array('Nama' => 'Muhammad Ilhamsyah', 'Email' => 'muhilhamsyah395@gmail.com'),
        165 => array('Nama' => 'Muhammad Irsyal Kamil', 'Email' => 'mirsyalk@gmail.com'),
        166 => array('Nama' => 'Muhammad Izzudin', 'Email' => 'chesmestesiss@gmail.com'),
        167 => array('Nama' => 'Muhammad Radhina Rahman Sapta Putra Wardana', 'Email' => 'radirahman7@gmail.com'),
        168 => array('Nama' => 'Muhammad Reza Fahlevi', 'Email' => 'rezanizer021@gmail.com'),
        169 => array('Nama' => 'Muhammad Rifky Haikal', 'Email' => 'mrifhaikal@gmail.com'),
        170 => array('Nama' => 'Muhammad Syarifudin', 'Email' => 'muhammad.syarifudin177@gmail.com'),
        171 => array('Nama' => 'Muhammad Yusuf', 'Email' => 'mhmmdys95@gmail.com'),
        172 => array('Nama' => 'Mukhamad Arief Hermanto', 'Email' => 'mukhamadarief23@gmail.com'),
        173 => array('Nama' => 'Nadya Laila Fitrianingrum', 'Email' => 'nadyalaila21@gmail.com'),
        174 => array('Nama' => 'Nena Yohanawati', 'Email' => 'nenayohanawati163@gmail.com'),
        175 => array('Nama' => 'Nito Fathur Rahman', 'Email' => 'nitofathur@gmail.com'),
        176 => array('Nama' => 'Noviandy Kusmanjaya', 'Email' => 'noviandy.kusmanjaya@yahoo.com'),
        177 => array('Nama' => 'Novira Setya Rini', 'Email' => 'savirasetia@gmail.com'),
        178 => array('Nama' => 'Nur Adi Indratomo', 'Email' => 'aditm33@gmail.com'),
        179 => array('Nama' => 'Nur Ahmad Fadil', 'Email' => 'fadil.stie@gmail.com'),
        180 => array('Nama' => 'Nur Kholifah Meizuki', 'Email' => 'nurkholifah.m@gmail.com'),
        181 => array('Nama' => 'Nur Muhamad Maftuh', 'Email' => 'nmmaftuh@gmail.com'),
        182 => array('Nama' => 'Nurlitta Shafitri', 'Email' => 'nurlittashafitri@gmail.com'),
        183 => array('Nama' => 'Nurul Khotimah', 'Email' => 'khotimahnurul263@gmail.com'),
        184 => array('Nama' => 'Osama Jundi Abdillah', 'Email' => 'osanaioya@gmail.com'),
        185 => array('Nama' => 'Ponco Hadi Saputra', 'Email' => 'poncohadisaputra@gmail.com'),
        186 => array('Nama' => 'Pridadi Widiarto Putra', 'Email' => 'utha.pwp@gmail.com'),
        187 => array('Nama' => 'Pujianto', 'Email' => 'pujiantososrobahu@gmail.com'),
        188 => array('Nama' => 'Putra Meza Ramadhan', 'Email' => 'putramezar@gmail.com'),
        189 => array('Nama' => 'Putri Permata Mellinia.A.Md', 'Email' => 'putripermata7889@gmail.com'),
        190 => array('Nama' => 'Rachmad Noviandri', 'Email' => 'rachmadnoviandri@gmail.com'),
        191 => array('Nama' => 'Raden Mochamad Rizky Marsiandi Dana Atmaja', 'Email' => 'raden.rizki@ymail.com'),
        192 => array('Nama' => 'Rafly Zeldhan', 'Email' => 'zeldhan@gmail.com'),
        193 => array('Nama' => 'Rahmat Harahap', 'Email' => 'rahmathrp40@gmail.com'),
        194 => array('Nama' => 'Raihan Zulkarnain', 'Email' => 'raihanzulkarnain123@gmail.com'),
        195 => array('Nama' => 'Rajib Himawan', 'Email' => 'rajibgandi1997@gmail.com'),
        196 => array('Nama' => 'Ramadhannu Try Utomo', 'Email' => 'ramadhannu.utomo@gmail.com'),
        197 => array('Nama' => 'Rangga Saputra Priyanto', 'Email' => 'saputrarangga82@gmail.com'),
        198 => array('Nama' => 'Rapiut Dahruja', 'Email' => 'jajats949@gmail.com'),
        199 => array('Nama' => 'Refita Aulina', 'Email' => 'refitaaulina25@gmail.com'),
        200 => array('Nama' => 'Rendy Septian Fadhilla', 'Email' => 'rendy.fadhilla@gmail.com'),
        201 => array('Nama' => 'Rian Adam', 'Email' => 'rianadam58@gmail.com'),
        202 => array('Nama' => 'Rima Desmiarni', 'Email' => 'rimanadean@gmail.com'),
        203 => array('Nama' => 'Rio Aulia Marsiano', 'Email' => 'rioauliamarsiano@gmail.com'),
        204 => array('Nama' => 'Riska Phillia Br Ginting', 'Email' => 'riskaphillia08@gmail.com'),
        205 => array('Nama' => 'Riska Pujiastuti', 'Email' => 'riskapujiastuti12@gmail.com'),
        206 => array('Nama' => 'Riyansah Jaya', 'Email' => 'riyansyahjaya60@gmail.com'),
        207 => array('Nama' => 'Rizal Budiawan', 'Email' => 'rizalbud1031@yahoo.com'),
        208 => array('Nama' => 'Rizki Dea Darmawan', 'Email' => 'bocorkiki@gmail.com'),
        209 => array('Nama' => 'Rizky Agusriansyah', 'Email' => 'rizkyagusriansyah@gmail.com'),
        210 => array('Nama' => 'Rizky Septina Kusuma Dewi', 'Email' => 'rizkyatwork@gmail.com'),
        211 => array('Nama' => 'Robby Hendrawan', 'Email' => 'robbyhendrawann23@gmail.com'),
        212 => array('Nama' => 'Robi Yudrianto', 'Email' => 'robiyudrianto2608@gmail.com'),
        213 => array('Nama' => 'Roma Anggiadini', 'Email' => 'romaanggiadini15@gmail.com'),
        214 => array('Nama' => 'Ruslan Rasmedi Saputra', 'Email' => 'alansaputra699@gmail.com'),
        215 => array('Nama' => 'Rusmanidar', 'Email' => 'rosemanydare@gmail.com'),
        216 => array('Nama' => 'Sahadah Hidayati', 'Email' => 'sahadahhidayati07@gmail.com'),
        217 => array('Nama' => 'Salim Fakhry', 'Email' => 'salimfahri45448@gmail.com'),
        218 => array('Nama' => 'Saliman', 'Email' => 'salim.fathin@gmail.com'),
        219 => array('Nama' => 'Samuel Putra Bahari', 'Email' => 'samuel.bahari98@gmail.com'),
        220 => array('Nama' => 'Sarah Firlyza', 'Email' => 'firlyzas@gmail.com'),
        221 => array('Nama' => 'Sendy Firdaus', 'Email' => 'shendy.firdaus9@gmail.com'),
        222 => array('Nama' => 'Shena Julian Irfan', 'Email' => 'shenajulianirfan@gmail.com'),
        223 => array('Nama' => 'Shofi Shibghatillah Shulhiddar', 'Email' => 'opijcd@gmail.com'),
        224 => array('Nama' => 'Sidk Wicaksono Ilham Ratri', 'Email' => 'sidikagito@gmail.com'),
        225 => array('Nama' => 'Silka Azzahra Shafa Aulia', 'Email' => 'silkaaulia@gmail.com'),
        226 => array('Nama' => 'Silvia Christine H', 'Email' => 'silviachrstn24@gmail.com'),
        227 => array('Nama' => 'Siti Maisyaroh', 'Email' => 'sitimaisyrh25@gmail.com'),
        228 => array('Nama' => 'Siti Nurjanah', 'Email' => 'janahbisa96@gmail.com'),
        229 => array('Nama' => 'Sobah Alhaddad', 'Email' => 'soba2806@gmail.com'),
        230 => array('Nama' => 'Soni Angga Purnama', 'Email' => 'nugrahenianindya2@gmail.com'),
        231 => array('Nama' => 'Suci Maulidiyah', 'Email' => 'sucimaulidya31@gmail.com'),
        232 => array('Nama' => 'Sugeng Teguh Prihatin', 'Email' => 'sugengteguh59@gmail.com'),
        233 => array('Nama' => 'Sumdi Rahayu', 'Email' => 'sumdi.gayu@gmail.com'),
        234 => array('Nama' => 'Sutiarna', 'Email' => 'sutiarna09@gmail.com'),
        235 => array('Nama' => 'Syamsul Anwar', 'Email' => 'sam_aid@yahoo.com'),
        236 => array('Nama' => 'Syarifudin Nurhidayat', 'Email' => 'syarifudin6276@gmail.com'),
        237 => array('Nama' => 'Taupik Hidayat', 'Email' => 'taupikhidayat121@gmail.com'),
        238 => array('Nama' => 'Tegar Bonaventura Belo Ola', 'Email' => 'tegarbeloola@gmail.com'),
        239 => array('Nama' => 'Teguh Supriyantono', 'Email' => 'teguh.srikandi46@gmail.com'),
        240 => array('Nama' => 'Teja Surahman', 'Email' => 'teja15surahman@gmail.com'),
        241 => array('Nama' => 'Thirdo Setyo Arif', 'Email' => 'thirdosetyo.a@gmail.com'),
        242 => array('Nama' => 'Thomas Satrio Lelono', 'Email' => 'thomaslelono@gmail.com'),
        243 => array('Nama' => 'Thomi Panca Nugrah', 'Email' => 'thomipanca@gmail.com'),
        244 => array('Nama' => 'Tirta Panditio Azuri', 'Email' => 'tirtazuri@gmail.com'),
        245 => array('Nama' => 'Ujang Ahmad Satibi', 'Email' => 'ujangahmadsatibi7@gmail.com'),
        246 => array('Nama' => 'Vidia Eka Saputri', 'Email' => 'vidia.ekas@gmail.com'),
        247 => array('Nama' => 'Vio Fathoni', 'Email' => 'viofathoni93@gmail.com'),
        248 => array('Nama' => 'Vitri Jamilatul Mugni', 'Email' => 'vitri@ymail.com'),
        249 => array('Nama' => 'Wahyu Maulana Mustafa', 'Email' => 'wahyumustafa78@gmail.com'),
        250 => array('Nama' => 'Wisnu Aji Triwibowo', 'Email' => 'wisnuajit.w@gmail.com'),
        251 => array('Nama' => 'Wisnu Hendarto', 'Email' => 'wisnuhendarto1902@gmail.com'),
        252 => array('Nama' => 'Witta Aisyah Dewanti', 'Email' => 'witta.daisyah@gmail.com'),
        253 => array('Nama' => 'Yasir Mubarok', 'Email' => 'yasir.mbrk10@gmail.com'),
        254 => array('Nama' => 'Yayang Caesar Tinawa', 'Email' => 'yayangtinawa15@gmail.com'),
        255 => array('Nama' => 'Yoan Indrian', 'Email' => 'yoanindrian@yahoo.co.id'),
        256 => array('Nama' => 'Yoga Pratama Geofanny', 'Email' => 'yogageofanny18@gmail.com'),
        257 => array('Nama' => 'Yohanes Kurniawan Santosa', 'Email' => 'yohaneskurniawans.33@gmail.com'),
        258 => array('Nama' => 'Yuda Prasetiyadi', 'Email' => 'yuda.prasetiyadi555@gmail.com'),
        259 => array('Nama' => 'Yudhistira Nurnugroho', 'Email' => 'yudhislibra911@gmail.com'),
        260 => array('Nama' => 'Zulfaqar Maulana', 'Email' => 'zul.maul@gmail.com'),
        261 => array('Nama' => 'KIKI ARIANTI ARITONANG', 'Email' => 'kikiariantiaritonang@gmail.com'),
        262 => array('Nama' => 'GITA SWARA MAHARDHIKA', 'Email' => 'mahardhikaswaragita28@gmail.com'),
        263 => array('Nama' => 'NUR RACHMAWATI', 'Email' => 'nrachmawati.s@gmail.com'),
        264 => array('Nama' => 'FARAH DIBA SAMIYAH', 'Email' => 'dibasamiya18@gmail.com'),
        265 => array('Nama' => 'HERMAWATI', 'Email' => 'mandhymanda8@gmail.com'),
        266 => array('Nama' => 'M. IRHAM', 'Email' => 'muhammadirham927@gmail.com'),
        267 => array('Nama' => 'MUH AZIS IRWANSYAH', 'Email' => 'azisirwansyah@gmail.com'),
        268 => array('Nama' => 'FAJAR FEBRIYANTO', 'Email' => 'febriyanto.fajar@gmail.com'),
        269 => array('Nama' => 'RIAN MULIANA', 'Email' => 'rianmuliana10@gmail.com'),
        270 => array('Nama' => 'MIFTAH RIZKI KARIEM PUTRA', 'Email' => 'rizki.miftah040@gmail.com'),
        271 => array('Nama' => 'WINDHA AYU AGTIYANI', 'Email' => 'ayuagtiyani04@gmail.com'),
        272 => array('Nama' => 'LUCKY SETIAWAN', 'Email' => 'luckysetiawan419@gmail.com'),
        273 => array('Nama' => 'KHOIRUL MIFTAH A PRATOMO', 'Email' => 'khoirulmiftah17@gmail.com'),
        274 => array('Nama' => 'DIMAS KURNIAWAN', 'Email' => 'dimasbs08@gmail.com'),
        275 => array('Nama' => 'PARASWATI', 'Email' => 'rarasw176@gmail.com'),
        276 => array('Nama' => 'SOLMERIANA SINAGA', 'Email' => 'sinaga.solmeriana@gmail.com'),
        277 => array('Nama' => 'PANDI ABDUL ROHMAN', 'Email' => 'sariwangi15@gmail.com'),
        278 => array('Nama' => 'ANTHONIUS SAMUEL W', 'Email' => 'anthoniussamuell@gmail.com'),
        279 => array('Nama' => 'EKA ROSITA', 'Email' => 'kak.rositae@gmail.com'),
        280 => array('Nama' => 'DEDDY INDRAWAN', 'Email' => 'deddyifa@gmail.com'),
        281 => array('Nama' => 'INDRA HERMAWAN', 'Email' => 'dra.hermawan81@gmail.com'),
        282 => array('Nama' => 'MUHAMMAD RIDWAN MASRI', 'Email' => 'juventusmazri@gmail.com'),
        283 => array('Nama' => 'AYIB PRIHATIN', 'Email' => 'ayibprihatin@gmail.com'),
        284 => array('Nama' => 'ZAENAL ALI', 'Email' => 'zaenal.ali4ka02@gmail.com'),
        285 => array('Nama' => 'HAIRUN AGUSTINO', 'Email' => 'hairunagustino@gmail.com'),
        286 => array('Nama' => 'ISRA TYPOGRAPHY S', 'Email' => 'isratypography@gmail.com'),
        287 => array('Nama' => 'LUKY HERMAWAN', 'Email' => 'lukyhermawan92@gmail.com'),
        288 => array('Nama' => 'MUHAMMAD DIMAS', 'Email' => 'dimass.muhammad@gmail.com'),
        289 => array('Nama' => 'AWAL APRIYANSAH', 'Email' => 'awalapriyansah@gmail.com'),
        290 => array('Nama' => 'HARVIANDI IRFANI', 'Email' => 'harviandiirfan@gmail.com'),
        291 => array('Nama' => 'IIN SUGIARTO', 'Email' => 'iinsugiarto135@gmail.com'),
        292 => array('Nama' => 'TAUFFAN MATUSEA', 'Email' => 'tauffan.matusea@gmail.com'),
        293 => array('Nama' => 'EGI BAGUS WIJOYONO', 'Email' => 'eggy.way@gmail.com'),
        294 => array('Nama' => 'ACHMAD SYARIFUDIN', 'Email' => 'mbolpeppy1@gmail.com'),
        295 => array('Nama' => 'RIAN KENEDY', 'Email' => 'rian81287@gmail.com'),
        296 => array('Nama' => 'HENDI NOPIANDI', 'Email' => 'hendi_nopiandi@yahoo.co.uk'),
        297 => array('Nama' => 'DEKY RACHMAT SUGIARTO', 'Email' => 'deky.sugi@gmail.com'),
        298 => array('Nama' => 'MOCHAMAD RIZKI AGUSTIANA', 'Email' => 'agustianrizki85@gmail.com'),
        299 => array('Nama' => 'ABDUL MUKTI', 'Email' => 'abdulmukti.am90@gmail.com'),
        300 => array('Nama' => 'ABDUL MUADZ', 'Email' => 'abdulmuadz0895@gmail.com'),
        301 => array('Nama' => 'H. ADHITYA FERDIANSYAH', 'Email' => 'adhitya.1106@gmail.com'),
        302 => array('Nama' => 'GUNAWAN', 'Email' => 'awanxhans@gmail.com'),
        303 => array('Nama' => 'SAPTO NUGROHO', 'Email' => 'nugroho77717@ymail.com'),
        304 => array('Nama' => 'YAN HARI PURNOMO', 'Email' => 'yanhari32@gmail.com'),
        305 => array('Nama' => 'RIZAL AMIN FAELASUF (Nonaktif)', 'Email' => 'rizalaminfaelasuf@gmail.com'),
        306 => array('Nama' => 'M ADITYA VETTO P', 'Email' => 'vetto.aditya@gmail.com'),
        307 => array('Nama' => 'IRJAN HARYONO', 'Email' => 'irjanharyono@gmail.com'),
        308 => array('Nama' => 'BOY SARDO HARRIOSTA R.', 'Email' => 'boysardoclover14@gmail.com'),
        309 => array('Nama' => 'DWI CANDRA WINOTO WIDIARTO', 'Email' => 'dwicandrawinotowidiarto@gmail.com'),
        310 => array('Nama' => 'WARDANA JAYA JASMITHA', 'Email' => 'wardanarockvanca@gmail.com'),
        311 => array('Nama' => 'ESA ANUGRAHENI', 'Email' => 'anugraheniesa@gmail.com'),
        312 => array('Nama' => 'DAVY ANWAR DANI', 'Email' => 'davy17anwar@gmail.com'),
        313 => array('Nama' => 'FARHAN HIDAYAT', 'Email' => 'farhanhidayat1291@gmail.com'),
        314 => array('Nama' => 'IKWAN NURDIANTO', 'Email' => 'rumputpagi77@gmail.com'),
        315 => array('Nama' => 'WAHYU HARYANTO', 'Email' => 'wahyuharyanto6@gmail.com'),
        316 => array('Nama' => 'RIZA ARDHIYANSAH', 'Email' => 'ardhiyansahriza@gmail.com'),
        317 => array('Nama' => 'VISIANTO HARI WIBOWO', 'Email' => 'visi08158757273@gmail.com'),
        318 => array('Nama' => 'AGUNG WIJAYAKUSUMA PUTRA', 'Email' => 'agungwkp@gmail.com'),
        319 => array('Nama' => 'EVA SARI TUMANGGOR', 'Email' => 'evasari705@gmail.com'),
        320 => array('Nama' => 'ALEX STEAVEN SITOMPUL', 'Email' => 'asteaven@yahoo.com'),
        321 => array('Nama' => 'DEVIANA DWI PUSPASARI', 'Email' => 'devianadwipuspasari92@gmail.com'),
        322 => array('Nama' => 'ARIF RACHMAN AJIZ', 'Email' => 'arifrachmanajiz2@gmail.com'),
        323 => array('Nama' => 'SAMUEL PARNINGOTAN HUTAHAEN', 'Email' => 'shutahaean00@gmail.com'),
        324 => array('Nama' => 'FREDY WB SITOMPUL', 'Email' => 'fredywbs@gmail.com'),
        325 => array('Nama' => 'HAMZAH MARTAMANGGALA', 'Email' => 'hamzahmartamanggala@gmail.com'),
        326 => array('Nama' => 'Edrisimon', 'Email' => 'thalitahamra@gmail.com'),
        327 => array('Nama' => 'DAVID FRANS HASIBUAN', 'Email' => 'david.hasibuan@gmail.com'),
        328 => array('Nama' => 'ACHMAD FUADI', 'Email' => 'uadnakumi86@gmail.com'),
        329 => array('Nama' => 'RAMADONI FRAIDAYANTO', 'Email' => 'ramadonifraidayanto@gmail.com'),
        330 => array('Nama' => 'IRFAN', 'Email' => 'irfan31sa@gmail.com'),
        331 => array('Nama' => 'HENDRI WAHYUDI', 'Email' => 'hendriwahyudi5@gmail.com'),
        332 => array('Nama' => 'RISKY WIDIYANTORO', 'Email' => 'riskywidiyantoro8@gmail.com'),
        333 => array('Nama' => 'AHMAD RAMDANI', 'Email' => 'ahmadramdani219@gmail.com'),
        334 => array('Nama' => 'BINSAR SELAMAT', 'Email' => 'bnzr766hi@gmail.com'),
        335 => array('Nama' => 'MUHAMAD YUNUS', 'Email' => 'yunusthamrin91@gmail.com'),
        336 => array('Nama' => 'AFIF AMRULLAH SAIMIMMA', 'Email' => 'afifsaimimma@yahoo.com'),
        337 => array('Nama' => 'ANGGIT FASYAMTAMA', 'Email' => 'mas.anggit.email@gmail.com'),
        338 => array('Nama' => 'KHORI KUSUMANINGRUM', 'Email' => 'khori0557@gmail.com'),
        339 => array('Nama' => 'RAINBOW EGGER DAMANIK', 'Email' => 'eggerrainbow@gmail.com'),
        340 => array('Nama' => 'BARNU ALI', 'Email' => 'barnusukses@gmail.com'),
        341 => array('Nama' => 'RAHMADI WIANGGA', 'Email' => 'rahmadi.wiangga@gmail.com'),
        342 => array('Nama' => 'BUDI MULYANA', 'Email' => 'bmmulyana@gmail.com'),
        343 => array('Nama' => 'ISAM ADI AURI', 'Email' => 'isam_adi@yahoo.com'),
        344 => array('Nama' => 'OKI OKTAVIA BAGUS', 'Email' => 'okibagus23@gmail.com'),
        345 => array('Nama' => 'PUTRI SETIA FITRI', 'Email' => 'putsefi79@gmail.com'),
        346 => array('Nama' => 'HENDRO NUGROHO', 'Email' => 'hendronugroho84@gmail.com'),
        347 => array('Nama' => 'NATHAN ROMLEN MANGARA', 'Email' => 'nathan.lumbanraja@gmail.com'),
        348 => array('Nama' => 'SIGIT SAPUTRO', 'Email' => 'sgtspt69@gmail.com'),
        349 => array('Nama' => 'REZA SYAHDEWO PRATOMO', 'Email' => 'rsyahdewopratomo@gmail.com'),
        350 => array('Nama' => 'RIO ELBOMA YUENDI', 'Email' => 'rioelboma@gmail.com'),
        351 => array('Nama' => 'AGUNG NUGROHO', 'Email' => 'andsense86@gmail.com'),
        352 => array('Nama' => 'SOBBRI ABBEN SARBENI', 'Email' => 'sobbri.as@gmail.com'),
        353 => array('Nama' => 'SOFIAN MAULANA', 'Email' => 'nurhasanahlitan@gmail.com'),
        354 => array('Nama' => 'DAHRIANSYAH PUTRA PRATAMA', 'Email' => 'dahriansyahputrapratama@gmail.com'),
        355 => array('Nama' => 'MAHMUDI PARINDURI', 'Email' => 'parinduri19group@gmail.com'),
        356 => array('Nama' => 'DWI KUNCORO', 'Email' => 'dwik28@gmail.com'),
        357 => array('Nama' => 'ARIEF RAHMAN', 'Email' => 'arief.ar29@gmail.com'),
        358 => array('Nama' => 'DJAMAL NASRI', 'Email' => 'djamal.nasri@gmail.com'),
        359 => array('Nama' => 'EKO PRASETYO', 'Email' => 'thiyo.ug90@gmail.com'),
        360 => array('Nama' => 'TEDY SASONO', 'Email' => 'tedy.sasono@gmail.com'),
        361 => array('Nama' => 'MUHAMAD SYAUQY FADILLAH', 'Email' => 'muhamadsyauqy@gmail.com'),
        362 => array('Nama' => 'RIZKY ANGGA LUKITA', 'Email' => 'rizkyanggalukita@gmail.com'),
        363 => array('Nama' => 'DANU RACHMANTO', 'Email' => 'danuorder@gmail.com'),
        364 => array('Nama' => 'DUWI SETIAWAN', 'Email' => 'dwiajah559@gmail.com'),
        365 => array('Nama' => 'ABDUL AZIZ JAELANI', 'Email' => 'abdul.aziz.jaelani.91@gmail.com'),
        366 => array('Nama' => 'AYU NABILA PASHA', 'Email' => 'ayunabilapasya98@gmail.com'),
        367 => array('Nama' => 'CENDIKYA TRI NUGRAHA', 'Email' => 'cendikyatrin@gmail.com'),
        368 => array('Nama' => 'MUHAMMAD REZA RESPATI', 'Email' => 'respati310316@gmail.com'),
        369 => array('Nama' => 'M FAHMI SURYADINATA', 'Email' => 'vahmis@gmail.com'),
        370 => array('Nama' => 'ENDAY', 'Email' => 'nday21leo@gmail.com'),
        371 => array('Nama' => 'DEDDI LESMANA', 'Email' => 'deylesmana@gmail.com'),
        372 => array('Nama' => 'GELENT FATARAJAYA', 'Email' => 'gelent83@gmail.com'),
        373 => array('Nama' => 'HADIYANTO', 'Email' => 'hadiyanto354@gmail.com'),
        374 => array('Nama' => 'OLYM PARLINDUNGAN SIMAREMARE', 'Email' => 'olymred23@gmail.com'),
        375 => array('Nama' => 'AGUNG NUR HIKMAH', 'Email' => 'agung_nurhikmah82@yahoo.co.id'),
        376 => array('Nama' => 'ADE TRY JUNIANSYAH', 'Email' => 'adetryjuniansyah@gmail.com'),
        377 => array('Nama' => 'BENNY ASSIAM SYUIB', 'Email' => 'assiambenie15@yahoo.co.id'),
        378 => array('Nama' => 'AJAD SUDRAJAD', 'Email' => 'aboutme.ajad15@gmail.com'),
        379 => array('Nama' => 'ROYFI MAULANA MASUM', 'Email' => 'royfim29@gmail.com'),
        380 => array('Nama' => 'IYAN ALAWI', 'Email' => 'nadoiyan@gmail.com'),
        381 => array('Nama' => 'IMAM KUSRI', 'Email' => 'imam.kusri@gmail.com'),
        382 => array('Nama' => 'FAHRUL RIZKY AULIA', 'Email' => 'fahrulrizkyaulia@gmail.com'),
        383 => array('Nama' => 'SITI NURLAILA', 'Email' => 'sitinurlaila335@gmail.com'),
        384 => array('Nama' => 'HERU SETIAWAN', 'Email' => 'setiawan1926@gmail.com'),
        385 => array('Nama' => 'ABDURRASYID AMRULLAH', 'Email' => 'abdurrasyid.amrullah@gmail.com'),
        386 => array('Nama' => 'MOHAMMAD FAJRIN', 'Email' => 'ajinzty@gmail.com'),
        387 => array('Nama' => 'KHAIRUL AMRI', 'Email' => 'amri26012019@gmail.com'),
        388 => array('Nama' => 'BAYU ADRI PUTRA', 'Email' => 'bayuadriputraa@gmail.com'),
        389 => array('Nama' => 'WIBI ARYA PUTRA', 'Email' => 'wibi27arya@gmail.com'),
        390 => array('Nama' => 'DONI HARIYANTO', 'Email' => 'don.nigell@gmail.com'),
        391 => array('Nama' => 'AHMAD ZAKI', 'Email' => 'zack.delonge@gmail.com'),
        392 => array('Nama' => 'WISNU WARDANA', 'Email' => 'pulautidungnews@gmail.com'),
        393 => array('Nama' => 'MUHAMMAD NAUFAL', 'Email' => 'm.naufalle@gmail.com'),
        394 => array('Nama' => 'MUHAMAD ABDUL LATIF', 'Email' => 'latifian22@gmail.com'),
        395 => array('Nama' => 'DANIEL RONALD SINAGA', 'Email' => 'danielronaldds@gmail.com'),
        396 => array('Nama' => 'OSCAR SULAIMAN PUTRA', 'Email' => 'oscarbpbd@gmail.com'),
        397 => array('Nama' => 'MUHAMMAD FIKRI SAPUTRA', 'Email' => 'mfikrisaputraaa@gmail.com'),
        398 => array('Nama' => 'IBADURRAHMAN AL-BAYHAKI', 'Email' => 'ibadbayhaki@gmail.com'),
        399 => array('Nama' => 'ABDUL MALIK', 'Email' => 'aam.malik1183@gmail.com'),
        400 => array('Nama' => 'ANTON SUPRAPTO', 'Email' => 'antonbombom17@gmail.com'),
        401 => array('Nama' => 'AHMAD WAHYU ARDIANTO', 'Email' => 'awedocktor46@gmail.com'),
        402 => array('Nama' => 'M. YASIR ARAFAT', 'Email' => 'alfabetaecho@gmail.com'),
        403 => array('Nama' => 'DIERGA NOERSHAPALA', 'Email' => 'deargavala@gmail.com'),
        404 => array('Nama' => 'CHANDRA RUTS FAJARIE', 'Email' => 'chandrarutss@gmail.com'),
        405 => array('Nama' => 'CESI MINARTI ARITONANG', 'Email' => 'cesiminarti066@gmail.com'),
        406 => array('Nama' => 'SONI', 'Email' => 'soni.kaka8@gmail.com'),
        407 => array('Nama' => 'TEGUH SANTOSO', 'Email' => 'santosoo.teguh@gmail.com'),
        408 => array('Nama' => 'ANDY ALFRIANRY, S.IP', 'Email' => 'andy.alfianry@gmail.com'),
        409 => array('Nama' => 'MUHAMMAD ARIF ZAINAL M', 'Email' => 'arif.arsus@gmail.com'),
        410 => array('Nama' => 'FERGIAWAN ANUGERAH RAMADHAN', 'Email' => 'fergiawanar@gmail.com'),
        411 => array('Nama' => 'HENDRI PRIYATNA', 'Email' => 'hendri.ndi@gmail.com'),
        412 => array('Nama' => 'ANDI RACHMAD RAZAK', 'Email' => 'acongacoaco@gmail.com'),
        413 => array('Nama' => 'REZA KURNIA', 'Email' => 'rezakurnia1@yahoo.co.id'),
        414 => array('Nama' => 'OKI RINALDI', 'Email' => 'aldianoki16@gmail.com'),
        415 => array('Nama' => 'HENDRYKO JOHANES PANJAITAN', 'Email' => 'hendryko.johanes@gmail.com'),
        416 => array('Nama' => 'RIDWAN SYARIF', 'Email' => 'abdumusafir@gmail.com'),
        417 => array('Nama' => 'WANDI DWI SISWANTO', 'Email' => 'wandids@gmail.com'),
        418 => array('Nama' => 'YANDI HARIS MUNANDAR', 'Email' => 'yandiharis24@gmail.com'),
        419 => array('Nama' => 'ABDUL RACHMAN', 'Email' => 'man.abdulrachman@gmail.com'),
        420 => array('Nama' => 'DIMAS PRAYOGI', 'Email' => 'dimasprayogi00@gmail.com'),
        421 => array('Nama' => 'FAISAL YAMANI', 'Email' => 'faisalyamani12333@gmail.com'),
        422 => array('Nama' => 'SUHANDOKO MISBAHUL AMIN', 'Email' => 'suhandoko.ma@gmail.com'),
        423 => array('Nama' => 'TORANG LEO RENSIUS P', 'Email' => 'torangleo7@gmail.com'),
        424 => array('Nama' => 'ANDRIYANA SUPRIYATNA', 'Email' => 'andriyans290@gmail.com'),
        425 => array('Nama' => 'EKO SALIM', 'Email' => 'echosaliem@gmail.com'),
        426 => array('Nama' => 'AENUROFIK', 'Email' => 'rofikivank@gmail.com'),
        427 => array('Nama' => 'GUNAWAN', 'Email' => 'gunx.ball@gmail.com'),
        428 => array('Nama' => 'PRIMA SARI WIJOYOKUSUMO', 'Email' => 'lexave21@gmail.com'),
        429 => array('Nama' => 'DEVRIES MAKHFUZ DANUBRATHA', 'Email' => 'devriesmakhfuzdanubratha@gmail.com'),
        430 => array('Nama' => 'MUHAMMAD REZA SYAHPUTRA', 'Email' => 'rezasyah34@gmail.com'),
        431 => array('Nama' => 'KHADIJAH QUROTA"AIN', 'Email' => 'khadijahqa2822@gmail.com'),
        432 => array('Nama' => 'LIDIA P KAMBEY', 'Email' => 'lidia.kambey1984@gmail.com'),
        433 => array('Nama' => 'KRISMA SARI', 'Email' => 'krisma.sari96@gmail.com'),
        434 => array('Nama' => 'AHMAD FAUZI', 'Email' => 'ozzieprabu@gmail.com'),
        435 => array('Nama' => 'GALANG PERSADHA', 'Email' => 'galang_holic91@yahoo.com'),
        436 => array('Nama' => 'ACHMAD HUZAIFI', 'Email' => 'achmadhuzaifi07@gmail.com'),
        437 => array('Nama' => 'EKA PERMATA ADI', 'Email' => 'eka241085@gmail.com'),
        438 => array('Nama' => 'MUHAMAD FAUZAN ALI', 'Email' => 'ali.fauzan786@gmail.com'),
        439 => array('Nama' => 'ANDRIANTI', 'Email' => 'andrianti.85@gmail.com'),
        440 => array('Nama' => 'MUHAMMAD HAERUDIN', 'Email' => 'muhammadhaerudin81@gmail.com'),
        441 => array('Nama' => 'JAKA HARINNANTO WICAKSANA', 'Email' => 'jaka.harinnanto@gmail.com'),
        442 => array('Nama' => 'ILHAM ALI AKBAR', 'Email' => 'ilhambokir21@gmail.com'),
        443 => array('Nama' => 'MUHAMMAD RAZAK', 'Email' => 'bondar8415@gmail.com'),
        444 => array('Nama' => 'JIKI ALON SODIA S HUTAPEA', 'Email' => 'jikialon@gmail.com'),
        445 => array('Nama' => 'ANDI TRISNA DIANI', 'Email' => 'andidiani92@gmail.com'),
        446 => array('Nama' => 'JASON APRINADO PUTRA DESNITA', 'Email' => 'jasonaprinado92@gmail.com'),
        447 => array('Nama' => 'RICHARD FERDANA', 'Email' => 'ferdanarichard@gmail.com'),
        448 => array('Nama' => 'RIZKY HARWIGIANTONO', 'Email' => 'rizkygian21@gmail.com'),
        449 => array('Nama' => 'MADANI RAHMATULLOH', 'Email' => 'madanirahmatulloh19@gmail.com'),
        450 => array('Nama' => 'LATERZA MA\'MUR HARIS', 'Email' => 'laterzamamur@gmail.com'),
        451 => array('Nama' => 'FACHRUL ROHMAN', 'Email' => 'fachrulrohman69@gmail.com'),
        452 => array('Nama' => 'REDO ROMADONA', 'Email' => 'rdrmdn@gmail.com'),
        453 => array('Nama' => 'DEDI HERMAWAN', 'Email' => 'hermawandedi530@gmail.com'),
        454 => array('Nama' => 'GUNAWAN WIBISONO, ST.', 'Email' => 'gunawan.wibisono1183@gmail.com'),
        455 => array('Nama' => 'AHMAD FAUZI', 'Email' => 'fauzibasri2@gmail.com'),
        456 => array('Nama' => 'ALIF IMAM SANTOSO', 'Email' => 'aliffimams@gmail.com'),
        457 => array('Nama' => 'RUSMAN', 'Email' => 'rusmancapil123@gmail.com'),
        458 => array('Nama' => 'NANO MOSSELMAN', 'Email' => 'nmosselman90@gmail.com'),
        459 => array('Nama' => 'DEDE IRAWAN', 'Email' => 'dedefira84@gmail.com'),
        460 => array('Nama' => 'SANTI KARTIKA WATI', 'Email' => 'kartikawatisanti@gmail.com'),
        461 => array('Nama' => 'Petugas Ajib 2', 'Email' => 'fauzifahmi1998@gmail.com'),
        462 => array('Nama' => 'MARZONI HENDRA JAYA', 'Email' => 'marzonihendra@gmail.com'),
        463 => array('Nama' => 'LILYK AGUNG SEDAYU', 'Email' => 'naif.lilyk@gmail.com'),
        464 => array('Nama' => 'MIFTAHUL FITROH', 'Email' => 'afitfitrohid@gmail.com'),
        465 => array('Nama' => 'MUNAJAT', 'Email' => 'munajattea@gmail.com'),
        466 => array('Nama' => 'FAUZI FIRMANSYAH', 'Email' => 'thecankuzhie@gmail.com'),
        467 => array('Nama' => 'SYIFA RUSYDINA', 'Email' => 'rusydinasyifa19@gmail.com'),
        468 => array('Nama' => 'AGE HARRY WIJAYANTO', 'Email' => 'ageharry20@gmail.com'),
        469 => array('Nama' => 'FARHAN SALIMAN', 'Email' => 'aanfarhansaliman21@gmail.com'),
        470 => array('Nama' => 'SYAHRULI', 'Email' => 'syahrulliee@yahoo.com'),
        471 => array('Nama' => 'MUSSLIM RAKHMATULLAH', 'Email' => 'musslimrakhmatullah5023@gmail.com'),
        472 => array('Nama' => 'FIYHIFZDILLAH', 'Email' => 'fiyhifzdillah@gmail.com'),
        473 => array('Nama' => 'ALI RACHMAT SIREGAR', 'Email' => 'alirachmatsiregar@gmail.com'),
        474 => array('Nama' => 'TEODOR MEIMAN HAREFA', 'Email' => 'teodorh24@gmail.com'),
        475 => array('Nama' => 'MULYADI', 'Email' => 'mulyadish1976@gmail.com'),
        476 => array('Nama' => 'ICHSAN SANDI P', 'Email' => 'ichsansableng212@gmail.com'),
        477 => array('Nama' => 'DEDE SUPRIATNA', 'Email' => 'supriatnadede83@gmail.com'),
        478 => array('Nama' => 'HELDA YAN PRAMADYA PUSPA', 'Email' => 'heldayan27@gmail.com'),
        479 => array('Nama' => 'DENY DAMARA', 'Email' => 'denidamarax@gmail.com'),
        480 => array('Nama' => 'AFRIZAL LASMI', 'Email' => 'rizal.corta@gmail.com'),
        481 => array('Nama' => 'ACHMAD SYARIF', 'Email' => 'achmadsyarif59@gmail.com'),
        482 => array('Nama' => 'ZULFIKAR HELMI TUGINO', 'Email' => 'zulfikar.eci@gmail.com'),
        483 => array('Nama' => 'MAULANA LUKMANSYAH', 'Email' => 'lukmansyah.maulana18@gmail.com'),
        484 => array('Nama' => 'TAUFIK RAMDHAN', 'Email' => 'ramdhansuzuki@gmail.com'),
        485 => array('Nama' => 'Farrah Adzabi Sidiqi', 'Email' => 'farrahadzabisidiqi@gmail.com'),
        486 => array('Nama' => 'ICHWANUL ZAYUANDRA', 'Email' => 'himitsu_ichwanul@yahoo.com'),
        487 => array('Nama' => 'Rizqo Salahudin', 'Email' => 'rizqosalahudin09@gmail.com'),
        488 => array('Nama' => 'ANDHIKA PUTRA', 'Email' => 'andhika.putra0610@gmail.com'),
        489 => array('Nama' => 'MUHAMMAD ARDIANSYAH', 'Email' => 'ardiansyah689908@gmail.com'),
        490 => array('Nama' => 'SAPPE SIRAIT', 'Email' => 'sappesirait2019@gmail.com'),
        491 => array('Nama' => 'MUHAMAD HENDRA', 'Email' => '76hendra.m@gmail.com'),
        492 => array('Nama' => 'NUR ARDIANSYAH', 'Email' => 'niza1142@gmail.com'),
        493 => array('Nama' => 'ALI FIRMANSYAH', 'Email' => 'freymania85@gmail.com'),
        494 => array('Nama' => 'AGUS BUDIAWAN', 'Email' => 'agusbudiawan3@gmail.com'),
        495 => array('Nama' => 'FIKRI ABDILLAH', 'Email' => 'fikriyuyu8@gmail.com'),
        496 => array('Nama' => 'SUHANDRI', 'Email' => 'andriacc47@gmail.com'),
        497 => array('Nama' => 'AHMAD HAMIDI', 'Email' => 'hamidiahmad826@gmail.com'),
        498 => array('Nama' => 'NOOR HALIMAH', 'Email' => 'seehalim@gmail.com'),
        499 => array('Nama' => 'HARIANDI', 'Email' => 'hariandihamka9@gmail.com'),
        500 => array('Nama' => 'TOMMY JULIO ADRIAWAN', 'Email' => 'tommycv8@gmail.com'),
        501 => array('Nama' => 'MARYANTO', 'Email' => 'ibnu.sina240909@gmail.com'),
        502 => array('Nama' => 'FAJAR FIQH', 'Email' => 'fajarfiqh@gmail.com'),
        503 => array('Nama' => 'EKO HENDI PRASETYO', 'Email' => 'ekohendiprasetyo13@gmail.com'),
        504 => array('Nama' => 'ANDI', 'Email' => 'andissos1993@gmail.com'),
        505 => array('Nama' => 'KESA RAGIL PEBRIONO', 'Email' => 'kesapebriono@gmail.com'),
        506 => array('Nama' => 'HENDRA SETIAWAN', 'Email' => 'hendr4setiawan234@gmail.com'),
        507 => array('Nama' => 'HERI', 'Email' => 'heridjawaraajib@gmail.com'),
        508 => array('Nama' => 'DWI MEGAYANTI', 'Email' => 'dwi.megayanti89@gmail.com'),
        509 => array('Nama' => 'ANDI MUHAROM', 'Email' => 'anditrix@yahoo.com'),
        510 => array('Nama' => 'DANI ANDON SUSILO', 'Email' => 'daniandon66@gmail.com'),
        511 => array('Nama' => 'ANDRIANSYAH BUDI PRASTIA', 'Email' => 'andriansyahbp@yahoo.co.id'),
        512 => array('Nama' => 'YOHANES CHRISTIAN FIRMANSYAH', 'Email' => 'ychristianf@gmail.com'),
        513 => array('Nama' => 'FURKON', 'Email' => 'elfurkon123@gmail.com'),
        514 => array('Nama' => 'SUTISNA PRAYOGA', 'Email' => 'sutisna89prayoga@gmail.com'),
        515 => array('Nama' => 'AGUNG SETIAWAN', 'Email' => 'ibnuafar@gmail.com'),
        516 => array('Nama' => 'FERDIAN WAHYU PURNAMA', 'Email' => 'ferdianwp@gmail.com'),
        517 => array('Nama' => 'MOHAMMAD SUMARTO', 'Email' => 'marto467890@gmail.com'),
        518 => array('Nama' => 'IYAN SOFI ANSORI', 'Email' => 'iyansofiansori163@gmail.com'),
        519 => array('Nama' => 'A. SYAUQI ZAM ZAMI ZAIN', 'Email' => 'zamizein92@gmail.com'),
        520 => array('Nama' => 'PUTRI LUTHFIAH AULIA', 'Email' => 'auliaputri1198@gmail.com'),
        521 => array('Nama' => 'SALMAN ALFARISI', 'Email' => 'salmanalfarisif690@gmail.com'),
        522 => array('Nama' => 'LUKCY KURNIAWAN', 'Email' => 'mlukcy1980@yahoo.com'),
        523 => array('Nama' => 'CATUR PRASETYO', 'Email' => 'caturrrr23@gmail.com'),
        524 => array('Nama' => 'ABDUL SAMID HIDAYATULLAH', 'Email' => 'samidabdul@gmail.com'),
        525 => array('Nama' => 'CUCU SAFARUHWIN', 'Email' => 'cucusafar91@gmail.com'),
        526 => array('Nama' => 'RIAN FEBRIANSYAH', 'Email' => 'rianfs44@gmail.com'),
        527 => array('Nama' => 'ADI NUGROHO', 'Email' => 'adinugroho2284@gmail.com'),
        528 => array('Nama' => 'ANDIKA HADHI PUTRA', 'Email' => 'hadhi.putra8@gmail.com'),
        529 => array('Nama' => 'HADYAN JAMIEL', 'Email' => 'jamielhadyan@gmail.com'),
        530 => array('Nama' => 'LEOMART SITOMPUL', 'Email' => 'danielleomart@yahoo.co.id'),
        531 => array('Nama' => 'FREDY YOHANNES', 'Email' => 'fypurba@gmail.com'),
        532 => array('Nama' => 'AGUSTIAN ELFA KUSUMA', 'Email' => 'alfakusuma5@gmail.com'),
        533 => array('Nama' => 'ANDRIANI DEWI LESTARI', 'Email' => 'riaria2910@gmail.com'),
        534 => array('Nama' => 'MALIK ABDUL AZIS', 'Email' => 'malikabdulazis26@gmail.com'),
        535 => array('Nama' => 'HIDAYATULLAH', 'Email' => 'hidayatullahdayat777@gmail.com'),
        536 => array('Nama' => 'IMAM BUDI SANTOSO', 'Email' => 'imambudisantos@gmail.com'),
        537 => array('Nama' => 'LEJAR GALUH SURYANINGWAN', 'Email' => 'galuh26@gmail.com'),
        538 => array('Nama' => 'NANANG FARDHUAMSYAH', 'Email' => 'nanangalghany@gmail.com'),
        539 => array('Nama' => 'AVNNER FALCON SAKUL', 'Email' => 'avnnerfalcon@gmail.com'),
        540 => array('Nama' => 'BUDI FEBRYANSYAH', 'Email' => 'budifebryansyah02@gmail.com'),
        541 => array('Nama' => 'EKA HERDIYANA RISDIYANTO', 'Email' => 'ekaherdi007@gmail.com'),
        542 => array('Nama' => 'BERRY PERMANA', 'Email' => 'berrypermana13@gmail.com'),
        543 => array('Nama' => 'MUHAMMAD RIZAN', 'Email' => 'zanri1988@gmail.com'),
        544 => array('Nama' => 'HERDIANSYAH', 'Email' => 'herdi.syah81@yahoo.co.id'),
        545 => array('Nama' => 'AGUS PITRA YANTO', 'Email' => 'agus.pitrayanto@gmail.com'),
        546 => array('Nama' => 'SUPRIYADI', 'Email' => 'yadimaxez@gmail.com'),
        547 => array('Nama' => 'MUHAMAD WAHYU', 'Email' => 'abuuzair271@gmail.com'),
        548 => array('Nama' => 'RENDYANTO HERMAWAN', 'Email' => 'rendyrund8@gmail.com'),
        549 => array('Nama' => 'DWIKY PRATAMA', 'Email' => 'dwiky.pratamasm@gmail.com'),
        550 => array('Nama' => 'ILHAM MAULANA', 'Email' => 'emailnyayangpunya@gmail.com'),
        551 => array('Nama' => 'YUSUP MAULANA', 'Email' => 'yusuf.ym5180@gmail.com'),
        552 => array('Nama' => 'OKMAN QURTUBI', 'Email' => 'okman2610@gmail.com'),
        553 => array('Nama' => 'RICO AFRIANTO', 'Email' => 'ricoafrianto99@gmail.com'),
        554 => array('Nama' => 'AHMAD HERMAWAN', 'Email' => 'ahmadhermawan882@gmail.com'),
        555 => array('Nama' => 'NANDA FITRIA FARHANI', 'Email' => 'naand.26@gmail.com'),
        556 => array('Nama' => 'IRWAN NUGRAHA', 'Email' => 'nugrahairwan3@gmail.com'),
        557 => array('Nama' => 'HAMDI ASNAN', 'Email' => 'hamdi.asnan@gmail.com'),
        558 => array('Nama' => 'NUR ANISA', 'Email' => 'anisaadjmain@gmail.com'),
        559 => array('Nama' => 'AMBARINI SEKARSIH HANDAYANI', 'Email' => 'ambarinish@gmail.com'),
        560 => array('Nama' => 'FAHMI ASYROF HASMAR', 'Email' => 'famahasmar@gmail.com'),
        561 => array('Nama' => 'IRATAMA ARTAYASA', 'Email' => 'iratamaa@gmail.com'),
    );

    foreach ($data as $d) {
        $user = User::create([
            'name' => $d['Nama'],
            'email' => $d['Email']
        ]);

        $user->assignRole('surveyer');
    }
});

Route::group(['middleware' => ['role:surveyer']], function () {
    Route::resource('/ajib', SurveyController::class);
    Route::post('/tracking', [TrackingController::class, 'index']);
    Route::delete('/delete-survey', [SurveyController::class, 'destroy'])->name('delete-survey');
});
