name: cd-branch-production

on:
  push:
    branches:
      - magelang
  pull_request:
    branches:
      - magelang

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          port: 22
          script: |
            cd /var/www/html/magelang
            git clone https://github.com/asnur/sip-dev-laravel -b magelang
            cd magelang
            git pull origin magelang
            chown -R $USER:www-data storage
            chmod -R 775 storage
            composer install
