name: cd-branch-mobile

on:
  push:
    branches:
      - mobile-dev

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          port: 2244
          script: |
            cd /var/www/html/mobile/sip-dev-laravel
            chown -R $USER:www-data storage
            chmod -R 775 storage
            git pull origin mobile-dev
            composer install
